### ISSUE TITLE
Automating secrets for new repos

### ISSUE THREAD

**Issue by sellingsolutions** [unfor19/githubsecrets#11]
Hi!

What an amazing utility, thanks a bunch for sharing this!

I was wondering how to automate this a bit with bash?

./insert-secrets repository-name

```
#!/bin/bash

PRIVATE_KEY_NAME=SSH_PRIVATE_KEY_SERVER_NAME
PRIVATE_KEY=$(cat id_rsa)

PUBLIC_KEY_NAME=SSH_PUBLIC_KEY_SERVER_NAME
PUBLIC_KEY=$(cat id_rsa.pub)

echo "$PRIVATE_KEY_NAME\n$PRIVATE_KEY\n" | ghs secret-apply -p userProfileName -r $1
```

**Comment by sellingsolutions** [comment]
I'm sure that this is a no-brainer I'm just a novice when it comes to bash

**Comment by unfor19** [comment]
Thank you for the input! What are you trying to achieve here? The latest version works by adding secrets to multiple repositories.

So you can use `ghs secret-apply -p pname -r 'repo1,repo2'

What are you trying to automate? :)

**Comment by unfor19** [comment]
@sellingsolutions You can use the bash script that I wrote to test this application - https://github.com/unfor19/githubsecrets/blob/master/test_functionality.sh - I think it'll provide you a good base to the automation that you're seeking.

I'm closing this issue, feel free to keep commenting or re-opening this issue.
