### ISSUE TITLE
This project is a awesome!

### ISSUE THREAD

**Issue by kitsirota** [unfor19/githubsecrets#14]
I have a lot of secrets to manage, across a lot of repos and your project just saved me hours of work today and probably days over the next year!  Excellent documentation and I love that you have a --help for all the commands.

Is there any way to buy you a beer or to donate to keep this going?

Also for anyone on ubuntu 16.04 or 18.04, you may run into a small hiccup with keyring if you go the pip route right away.  Just run this to get going
```
apt-get install libdbus-glib-1-dev
pip install secretstorage dbus-python
pip install keyring
```

**Comment by unfor19** [comment]
Thank you @kitsirota !

Regarding the beer, if you any suggestions on how to improve this project, then it would be better than a beer :)

And thank you for your valuable input, I'll add it to the docs
