### ISSUE TITLE
Consider using a container with non-root user

### ISSUE THREAD

**Issue by php-coder** [unfor19/githubsecrets#5]
I see that example mounts the current directory to /root folder and (in 99%) it means that the container is running under root user. This is insecure and I suggest to [use a non-privileged user instead](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user).

**Comment by unfor19** [comment]
Yes, you are right. It's best practice to use USER instead of running as root. I'll change, thanks!

You can also open a PR and I'll merge it, either way thank you for your contribution

**Comment by unfor19** [comment]
Since users can mount whichever folder, such as - `/tmp/ghs`, `/home/myname/ghs/`, I'm dropping this, since there's no dangerous/malicious code which justifies this change.

P.S- I've tried applying this change, but it seems to be an overkill for such a simple application

**Comment by unfor19** [comment]
@php-coder - It's been a while, but I've set it up to run as non-root user
